export const CHANGE_SRC_CURRENCY_COUNTRY = 'CHANGE_SRC_CURRENCY_COUNTRY';
export const CHANGE_SRC_CURRENCY_VALUE = 'CHANGE_SRC_CURRENCY_VALUE';

export const CHANGE_TGT_CURRENCY_COUNTRY = 'CHANGE_TGT_CURRENCY_COUNTRY';
export const CHANGE_TGT_CURRENCY_VALUE = 'CHANGE_TGT_CURRENCY_VALUE';

export const FETCH_CURRENCY_CONVERTER_RATES_REQUEST = 'FETCH_CURRENCY_CONVERTER_RATES_REQUEST';
export const FETCH_CURRENCY_CONVERTER_RATES_SUCCESS = 'FETCH_CURRENCY_CONVERTER_RATES_SUCCESS';
export const FETCH_CURRENCY_CONVERTER_RATES_FAILURE = 'FETCH_CURRENCY_CONVERTER_RATES_FAILURE';